version: '3.8'

services:
  backend:
    build: ./
    container_name: calendarik-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: calendarik-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kukuruza26
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  pgdata:
